# This file contains values from Cookiecutter

default_context:
  project_name: "pypole"
  project_description: "Awesome `pypole` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "pypole"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "pypole"
  email: "michaelvolk1979@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
